import time

print("Tervetuloa Puolan Varsovaan!")
time.sleep(3)
print("Olet rikostutkija {syötetty käyttäjänimi mahdollisesti?}")
time.sleep(3)
print("Eilen myöhään yöllä Ilkka löydettiin murhattuna Varsovasta.")
time.sleep(7)
print("Sinun tehtäväsi on selvittää kuka murhasi Ilkan.")
time.sleep(5)
print("Apulaisrikostutkija on kerännyt sinulle viisi epäiltyä, jotka ovat karanneet eri lentokentille ympäri Eurooppaa. ")
time.sleep(8)
print("Käy haastattelemassa heitä ja selvitä kuka on murhaaja")
time.sleep(5)
print("mutta muista sinulla on vain 7 lentolippua eli voit lentää vain seitsemään eri kohteeseen, joten käytä ne harkiten.")
time.sleep(9)
print("Onnea matkaan!")
time.sleep(2)
valmis = input("Paina enter-näppäintä, kun olet valmis aloittamaan!")
